### Login empleado - jechava01@gmail.com
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "username": "jechava01@gmail.com",
    "password": "jjp085401"
}

### Login administrador - admin01@gmail.com
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "username": "admin01@gmail.com",
    "password": "admin123"
}

### Login - 08257@gmail.com
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "username": "08257@gmail.com",
    "password": "jorge0124"
}