###
GET http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiamVjaGF2YXJyaWEyNyIsInJvbGUiOiJFTVBMRUFETyIsInN1YiI6ImplY2hhdmFycmlhMjciLCJpYXQiOjE3NzMxMTExNDMsImV4cCI6MTc3MzExMTc0M30.EImti5F2JSrH1cZjEtfEySrvgo58jTrDncBJ9zPeBuQ
Accept: application/json

### Crear registros
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "userName": "jechavarria27",
    "email": "jechava01@gmail.com",
    "password": "jjp085401",
    "idRol": 2
}

### Crear registros
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "userName": "jj0827",
    "email": "08257@gmail.com",
    "password": "jorge0124",
    "idRol": 3
}

### Crear registros
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "userName": "adminpapel01",
    "email": "admin01@gmail.com",
    "password": "admin123",
    "idRol": 1
}

###
POST  http://localhost:8081/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYWRtaW5wYXBlbDAxIiwicm9sZSI6IkFETUlOSVNUUkFET1IiLCJzdWIiOiJhZG1pbnBhcGVsMDEiLCJpYXQiOjE3NjI3MjkwNDQsImV4cCI6MTc2MjcyOTM0NH0.-J7mK639zuXBRGp6Dx7ZqD2_a68DP8_tUCf07I3rNcA
Content-Type: application/json

{
    "userName": "JuanPablo00",
    "email": "pablo01@gmail.com",
    "password": "jpablo0870",
    "idRol": 3

}

###
DELETE http://localhost:8081/api/users/2




